apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-kflf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-kflf
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-kflf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-kflf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-kflf
    spec:
      containers:
      - image: quay.io/ysubrama_org/release-e2e-bundle-tenant/appstudio/dc-metro-map-kflf@sha256:7b97d138158c9a664cec6929db152c1d15cf012a8413b9fe014c29c605c09abf
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
